licenses(["notice"])

package(default_visibility = ["//visibility:private"])

cc_binary(
    name = "prefilter",
    srcs = ["prefilter.cc", "common.h"],
    deps = [
        "//external:base",
        "//external:boost",
    ],
    linkstatic = 1,
)
