licenses(["notice"])

package(default_visibility = ["//visibility:public"])

load("//rules:archive.bzl", "archive")

java_binary(
    name = "wata",
    srcs = glob(["*.java", "**/*.java"]),
    main_class = "Main",
)
