licenses(["notice"])

package(default_visibility = ["//visibility:private"])

load("//rules:deploy.bzl", "deploy")

deploy(
    name = "score",
    binary = "//iwiwi:score",
)

deploy(
    name = "chokudai",
    binary = "//ai/chokudai:chokudai.ar",
)
